### ISSUE TITLE
How to disable Heroku Metrics Agent Jar Download when not using heroku CLI

### ISSUE THREAD

**Issue by very-doge-wow** [heroku/heroku-java-metrics-agent#100]
I'm using heroku buildpacks using the CNB lifecycle creator directly to build a springboot maven application inside a containerized build process (GitLab CI). The download of the metrics jar fails, since I don't have internet access during build-time. How can I either
* disable download of the metrics agent jar
* set a different URL for the download to use an internal company mirror
without using the heroku CLI? 

I've tried setting the `HEROKU_METRICS_JAR_URL` as an environment variable as specified in the [platform spec](https://github.com/buildpacks/spec/blob/main/platform.md), but sadly to no avail.

This is the function that causes my problem: https://github.com/heroku/heroku-buildpack-jvm-common/blob/220ce5e4bc797cf4c385860fb820e7d396356bcc/lib/jvm.sh#L163

_Originally posted by @very-doge-wow in https://github.com/heroku/heroku-java-metrics-agent/issues/9#issuecomment-1482646349_

**Comment by Malax** [comment]
Hi @very-doge-wow, I'm not sure if we're looking at the correct thing here - Heroku has a dedicated repository for JVM related CNBs nowadays. It can be found here: https://github.com/heroku/buildpacks-jvm

Can you post a snippet from your build log where we can see the versions of the buildpacks being used are shown? The relevant bits are below this message:

`[INFO]     [creator]     ===> DETECTING`

**Comment by very-doge-wow** [comment]
Yeah that's why I've included the url to the line which causes the issue. The buildpack is this one: https://github.com/heroku/heroku-buildpack-jvm-common

The function is this:
https://github.com/heroku/heroku-buildpack-jvm-common/blob/220ce5e4bc797cf4c385860fb820e7d396356bcc/lib/jvm.sh#L163

And here's some job log:
```
===> ANALYZING
No previous image version found
Restoring data for SBOM from previous image
===> DETECTING
heroku/jvm      1.0.7
heroku/maven    1.0.3
heroku/procfile 2.0.0
===> RESTORING
===> BUILDING
[Installing OpenJDK]
[Installing Heroku JVM metrics agent]
[Error: Heroku Metrics Agent download failed]
Could not download Heroku Metrics Agent.
Please try again. If this error persists, please contact us:
https://help.heroku.com/
Details: HttpError(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("repo1.maven.org")), port: None, path: "/maven2/com/heroku/agent/heroku-java-metrics-agent/3.14/heroku-java-metrics-agent-3.14.jar", query: None, fragment: None }), source: Some(Error { kind: TimedOut, message: "connection timed out" }) }))
ERROR: failed to build: exit status 1
```

**Comment by Malax** [comment]
Thanks for posting the output! :) Yeah, you're looking at the wrong buildpack - the one you linked and opened the PR against is not the one you actually use. The correct one would be https://github.com/heroku/buildpacks-jvm/tree/main/buildpacks/jvm.

Another question, how would you expect the OpenJDK to be downloaded when you're building in an environment without internet access? The OpenJDK distribution is not bundled with the buildpack itself :(.

**Comment by Malax** [comment]
@very-doge-wow okay, good! I'll take a look and see if I can fix the issue you're having in the other repo. Shouldn't be a huge deal.

**Comment by very-doge-wow** [comment]
@Malax Thanks! Maybe you can take a look at this specific line: https://github.com/heroku/buildpacks-jvm/blob/3a3156a51a5e83485fa3470d04b0227aec473244/buildpacks/jvm/src/bin/heroku_metrics_agent_setup.rs#L25

Because setting this variable which is checked here to disable the metrics agent entirely doesn't seem to work (neither when simply setting it in the build process nor when setting it as specified in the platform spec for user-defined variables).

**Comment by Malax** [comment]
Hey @very-doge-wow - that environment variable you linked to is meant to disable the use of the metrics agent, not skipping the installation altogether. I've stirred up a PR for your feature request here: https://github.com/heroku/buildpacks-jvm/pull/444. I'll close this issue here since it's not related to the repo. Feel free to continue commenting in the linked PR! :)
